version: "3"

networks:
  soketi:
    driver: bridge

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4510-4530:4510-4530"
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs,s3
      - DEBUG=1
      - HOST_TMP_FOLDER=/tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - soketi
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      retries: 3
      timeout: 5s
